version: '3'

services:
  my-rails-app:
    container_name: my-rails-app
    build:
      context: .
      dockerfile: Dockerfile # 根据你的 Rails 应用 Dockerfile 配置
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - rails_demo
    # 更多的配置项可能包括端口映射、挂载卷等，根据你的需求添加

  my-nginx:
    container_name: my-nginx
    image: nginx:latest
    ports:
      - "80:80" # 如果需要使用其他端口，可以修改此处
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert.pem:/cert.pem
      - ./new_key.pem:/key.pem
    depends_on:
      - my-rails-app # 等待 Rails 应用启动后再启动 Nginx
    networks:
      - rails_demo
    # 其他配置项可以根据需要添加，比如 SSL 证书挂载等


networks:
  rails_demo:
    driver: bridge
